baseurl: ""
url: "minbio.github.io"
permalink: /:categories/:year/:month/:day/:title.html

# For inline code

# Site settings
title: Navin Lab
email: NNavin@mdanderson.org
description: "The Navin Laboratory at The University of Texas MD Anderson Cancer Center."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: DD1144
  secondary: DD1144
  third: ccc
  secondary-dark: 737373

category-list: [software, news]

# Team names, titles and social links
people:
- name: Nicholas Navin
  pic: nick
  position: Professor & Chair
  social:
    - title: twitter
      url: https://twitter.com/nicholas_navin
    - title: graduation-cap
      url: https://scholar.google.com/citations?user=e4mp7GoAAAAJ&hl=en
    - title: linkedin
      url: https://www.linkedin.com/in/nicholas-navin-6541b137


- name: Emi Sei
  pic: emi
  position: Research Group Leader
  social:
    - title: envelope
      url: mailto:ESei@mdanderson.org


- name: Shanshan Bai
  pic: shan
  position: Supv, Laboratory & Research
  social:
    - title: envelope
      url: mailto:SBai@mdanderson.org


- name: Tuan Tran
  pic: tuan
  position: Research Laboratory Manager
  social:
    - title: envelope
      url: mailto:TMTran2@mdanderson.org


- name: Jerome Lin
  pic: jerome
  position: Computational Scientist
  social:
    - title: envelope
      url: mailto:JLin9@mdanderson.org


- name: Heba Elgamal
  pic: heba
  position: Senior Research Assistant
  social:
      - title: envelope
        url: HElgamal@mdanderson.org



- name: Jianzhuo Li
  pic: jiahong
  position: Research Scientist
  social:
    - title: envelope
      url: mailto:JLi33@mdanderson.org



- name: Mitchell Rao
  pic: Mitchael
  position: Computational Scientist
  social:
    - title: envelope
      url: mailto:mmrao@mdanderson.org


- name: Chenling Tang
  pic: chenling
  position: Computational Scientist
  social:
    - title: envelope
      url: mailto:CTang4@mdanderson.org
    - title: linkedin
      url: https://www.linkedin.com/in/chenling-tang-900815138/

  
  
- name: Zhenna Xiao
  pic: zhenna
  position: Postdoctoral Fellow
  social:
      - title: envelope
        url: ZXiao1@mdanderson.org



- name: Nicolaas Baudoin
  pic: Nico
  position: Postdoctoral Fellow
  social:
    - title: envelope
      url: mailto:NBaudoin@mdanderson.org


- name: Rachel Dittmar
  pic: Rachel
  position: Postdoctoral Fellow
  social:
    - title: envelope
      url: mailto:RLDittmar@mdanderson.org
    - title: twitter
      url: https://twitter.com/RLDittmar
    - title: linkedin
      url: https://www.linkedin.com/in/racheldittmar



- name: Aatish Thennavan
  pic: Aatish
  position: Postdoctoral Fellow
  social:
    - title: envelope
      url: mailto:AThennavan@mdanderson.org


- name: Ryan Mulqueen
  pic: Ryan
  position: Postdoctoral Fellow
  social:
    - title: envelope
      url: mailto:rmulqueen@mdanderson.org


- name: Andres Nevarez
  pic: Andres
  position: Postdoctoral Fellow
  bio:
    Currently, my research is focused on understanding the landscape
    of de novo mutation in the human genome. 
  social:
    - title: envelope
      url: mailto:ajnevarez@mdanderson.org
    - title: twitter
      url: https://twitter.com/TechnicolorDres
    - title: linkedin
      url: https://www.linkedin.com/in/andresnevarezphd
    - title: share
      url: https://www.the-scientist.com/defining-the-triple-negative-breast-cancer-morpholome-71661 

- name: Haijing Jin
  pic: haijing
  position: Postdoctoral Fellow
  social:
    - title: envelope
      url: mailto:hjin3@mdanderson.org


- name: Rui Ye
  pic: ruiye
  position: Postdoctoral Fellow
  social:
      - title: envelope
        url: mailto:RYe@mdanderson.org


- name: Sidi Zhao
  pic: sidi
  position: Postdoctoral Fellow
  social:
    - title: envelope
      url: mailto:SZhao7@mdanderson.org
    - title: twitter
      url: https://twitter.com/sidizhao94
    - title: linkedin
      url: https://www.linkedin.com/in/sidizhao


- name: Yun Yan
  pic: yun
  position: Graduate Student
  social:
      - title: envelope
        url: YYan7@mdanderson.org



- name: Jie Ye
  pic: jie
  position: Graduate Student
  social:
      - title: envelope
        url: JYe1@mdanderson.org


- name: Yiyun Lin
  pic: yiyun
  position: Graduate Student
  social:
      - title: envelope
        url: ylin54@mdanderson.org


- name: Siyuan He
  pic: siyuan
  position: Graduate Student
  social:
      - title: envelope
        url: SHe2@mdanderson.org

- name: Junke (Kris) Wang
  pic: junke
  position: Graduate Student
  social:
      - title: envelope
        url: JWang48@mdanderson.org

- name: Ping Xu
  pic: pingxu
  position: Graduate Student
  social:
      - title: envelope
        url: pxu@mdanderson.org



- name: Lei Yang
  pic: leiyang
  position: Graduate Student
  social:
      - title: envelope
        url: LYang15@mdanderson.org


- name: Mariam Mosaad
  pic: mariam
  position: Graduate Student
  social:
      - title: envelope
        url: MMosaad@mdanderson.org


- name: Reem Elghaish
  pic: reem
  position: Graduate Student
  social:
      - title: envelope
        url: raelghaish@mdanderson.org


- name: Chante Bethell
  pic: chante
  position: Graduate Student
  social:
      - title: envelope
        url: CJBethell@mdanderson.org



# Alumni
alumni:


- name: Yong Wang
  pic: wangyong
  position: Postdoctoral Scientist
  social:
    - title: github
      url:

- name: Ruli Gao
  pic: ruli
  position: Postdoctoral Scientist
  social:
    - title: github
      url:

- name: Marco Leung
  pic: marco
  position: Undergraduate Researcher

- name: Pei-Ching Tsai
  pic: sai
  position: Undergraduate Researcher

- name: Charissa Kim
  pic: charissa
  position: phD Student
  social:
    - title: github
      url:

- name: Haowei Du
  pic: Haowei
  position: Undergraduate Student
  social:
    - title: github
      url:



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nicholas_navin
  - title: envelope
    url: mailto:NNavin@mdanderson.org
  - title: google
    url: https://scholar.google.com/citations?user=e4mp7GoAAAAJ&hl=en
  - title: linkedin
    url: https://www.linkedin.com/in/nicholas-navin-6541b137
